#!/bin/bash

echo "📋 Scout Databank Database Setup"
echo "================================"
echo ""
echo "To set up the database, go to your Supabase SQL Editor:"
echo ""
echo "🔗 https://supabase.com/dashboard/project/cxzllzyxwpyptfretryc/sql"
echo ""
echo "Then run the SQL script located at:"
echo "📄 schema/create_tables.sql"
echo ""
echo "After running the SQL, you can:"
echo "1. Run the seeding script: node seed-database.js"
echo "2. Start the dashboard: npm run dev"
echo "3. Visit: http://localhost:3000/dashboard"
echo ""
echo "The SQL script will create:"
echo "✅ Transactions table"
echo "✅ IoT telemetry tables"
echo "✅ Master dimension tables"
echo "✅ Agent infrastructure tables"
echo "✅ Row Level Security policies"
echo "✅ Sample data"
echo ""